image:
  repository: shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.1.1@sha256:11706de28d9ed9eb65bfa897f042a3b997f79ceed64e9410903f99d88450136b
service:
  main:
    ports:
      main:
        targetPort: 80
        port: 10154
        protocol: http
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
